# used with vscode rest-client https://open-vsx.org/extension/humao/rest-client

###
# get replica count
###
GET http://localhost:9090/ HTTP/1.1
content-type: text/plain

###
# set (POST) replica count
###
POST http://localhost:9090/scale HTTP/1.1
content-type: application/json

{"desiredReplicas": 7}

###
# get (GET) replica count via `/scale` 
###
GET http://localhost:9090/scale HTTP/1.1
content-type: text/plain

###
# grpc cant be tested in this file ::shrug::
###
# GET http://localhost:50051/IsActive HTTP/1.1
# content-type: grpc
# 
# use grpcurl
# grpcurl -plaintext localhost:50051 externalscaler.ExternalScaler.IsActive
# {
#   "result": true
# }

###
# healthcheck
###
GET http://localhost:9090/health HTTP/1.1
content-type: application/json

###
# fastapi metrics
###
GET http://localhost:8000/metrics HTTP/1.1
content-type: application/json

###
# get replica count
###
GET http://localhost:8000/jobs/get HTTP/1.1
content-type: application/json

###
# set job replica count e.g. `count=5&action=set`
###
POST http://localhost:8000/jobs/set?count=5&action=set HTTP/1.1
content-type: application/json

###
# increase job replica count e.g. `count=10&action=increase`
###
POST http://localhost:8000/jobs/set?count=10&action=increase HTTP/1.1
content-type: application/json
