# used with vscode rest-client https://open-vsx.org/extension/humao/rest-client

###
# get replica count
###
GET http://localhost:8000/scale HTTP/1.1
content-type: text/plain

###
# set replica count
###
POST http://localhost:8000/scale HTTP/1.1
content-type: application/json

{"desiredReplicas": 4}

###
# healthcheck
###
GET http://localhost:8000/health HTTP/1.1
content-type: application/json

###
# fastapi metrics
###
GET http://localhost:8000/metrics HTTP/1.1
content-type: application/json

###
# get replica count
###
GET http://localhost:8000/jobs/get HTTP/1.1
content-type: application/json

###
# set job replica count e.g. `count=5&action=set`
###
POST http://localhost:8000/jobs/set?count=5&action=set HTTP/1.1
content-type: application/json

###
# increase job replica count e.g. `count=10&action=increase`
###
POST http://localhost:8000/jobs/set?count=10&action=increase HTTP/1.1
content-type: application/json
